In [1]:
!pip install --upgrade openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Catalogos

## Tiendas-BI

Dado que el catalogo de tiendas se encuentra fragmentado, es necesario unificarlo.

In [3]:
cagsa= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda CAGSA.xlsx", engine="openpyxl")

vargas= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Casa Vargas.xlsx", engine="openpyxl")

coma= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Coma.xlsx", engine="openpyxl")

decasa= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Decasa.xlsx", engine="openpyxl")

duero= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Duero.xlsx", engine="openpyxl")

garis= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Garis.xlsx", engine="openpyxl")

rivera= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Gran Bodega.xlsx", engine="openpyxl")

soledad= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda La Soledad.xlsx", engine="openpyxl")

masbodega= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Mas Bodega.xlsx", engine="openpyxl")

miniabastos= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Mini Abastos.xlsx", engine="openpyxl")

z= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda PCZ.xlsx", engine="openpyxl")

promotora= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Promotora del Norte.xlsx", engine="openpyxl")

propasa= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Propasa.xlsx", engine="openpyxl")

sahuayo= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Sahuayo.xlsx", engine="openpyxl")

sanchez= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Sanchez.xlsx", engine="openpyxl")

lugo= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Santos Lugo.xlsx", engine="openpyxl")

super= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Su Super.xlsx", engine="openpyxl")

aki= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Super Aki.xlsx", engine="openpyxl")

toscano= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Vigil Toscano.xlsx", engine="openpyxl")

zorro= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Zorro Abarrotero.xlsx", engine="openpyxl")

parral= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Parral.xlsx", engine="openpyxl")

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [4]:
tdas=pd.concat([cagsa,vargas,coma,decasa,duero,garis,rivera,soledad,miniabastos,parral,
                z,promotora,propasa,sahuayo,sanchez,lugo,super,aki,toscano,zorro,masbodega])

tdas = tdas.replace(r'\s+', ' ', regex=True)

tdas=tdas.iloc[:,[0,1,2]]

/tmp/ipython-input-3825371896.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tdas=pd.concat([cagsa,vargas,coma,decasa,duero,garis,rivera,soledad,miniabastos,parral,

In [5]:
tdas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1672 entries, 0 to 78
Data columns (total 3 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Holding                       1672 non-null   object
 1   Código Punto de Venta Cadena  1672 non-null   object
 2   Nombre de Tienda              1672 non-null   object
dtypes: object(3)
memory usage: 52.2+ KB

In [6]:
tdas['Holding '].unique()

array(['CAGSA', 'Casa Vargas', 'COMA', 'DECASA', 'Duero', 'Garis',
       'Gran Bodega', 'La Soledad', 'Mini Abastos', 'Abastecedora Parral',
       'PCZ', 'Promotora Abarrotera del Norte', 'PROPASA', 'Sahuayo',
       'Grupo Sanchez', 'Casa Santos Lugo', 'Su Super', 'Super Aki',
       'Vigil Toscano', 'Zorro', 'Más Bodega'], dtype=object)

Dado que pueden existir identificadores que tengan repetición con otra cadena, se recurre a realizar una Key general: Cadena + Codigo

In [7]:
tdas['key_tda'] =tdas['Holding '].astype(str) + tdas['Código Punto de Venta Cadena'].astype(str)

tdas=tdas.iloc[:,[3]]

tdas.tail(5)

          key_tda
74   Más Bodega68
75   Más Bodega31
76   Más Bodega27
77  Más Bodega168
78  Más Bodega169

## Productos-BI

catalogo de productos general (construido con historicos). Solo para cuando me entreguen la información sin relacionar los codigos de material con los codigos del cliente

In [ ]:
ab=pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Catalogo_Productos.xlsx",
                 sheet_name="Catalogo",
                 engine="openpyxl")
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2982 entries, 0 to 2981
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Agrupador (C+V)         2982 non-null   object
 1   Satus SKU               2912 non-null   object
 2   >ATTP5                  2982 non-null   object
 3   Madre o hijo            434 non-null    object
 4   Largo                   2982 non-null   int64
 5   Inicio (2)              2982 non-null   object
 6   Variante (2)            1928 non-null   object
 7   Constante(6)            1929 non-null   object
 8   >Código Material*       2982 non-null   object
 9   >Desc. Código Material  2982 non-null   object
 10  >Marca                  2982 non-null   object
 11  SUBMARCA                2982 non-null   object
 12  Desc_Mayoreo            2982 non-null   object
 13  >ATTP4                  2982 non-null   object
 14  >Desc. Sector Material  2982 non-null   object
 15  Segmentacion            2982 non-null   object
 16  >N° Ply / Talla         2982 non-null   object
 17  Presentacion            2982 non-null   int64
 18  Empaquetado (Cj/Blt)    2982 non-null   int64
 19  Unidades                2982 non-null   int64
 20  >Kgr_empaq              1953 non-null   float64
dtypes: float64(1), int64(4), object(16)
memory usage: 489.4+ KB

In [ ]:
# selccionar columnas por index
ab= ab.iloc[:,[8,18]]

# renombrar las columnas
ab= ab.rename(columns={'>Código Material*': "CODIGO"})

ab = ab.replace(r'\s+', ' ', regex=True)

ab.head()

       CODIGO  Empaquetado (Cj/Blt)
0  AB11000855                    24
1  AB10335148                    48
2  AB10331522                    60
3  AB10335179                    48
4  AB10335315                    48

## Puebla-Materiales

In [ ]:
mat_softys=pd.read_excel('/content/drive/Shareddrives/Catalogos_SO/Catalogo_Puebla.xlsx')
mat_softys=mat_softys.replace(r'\s+', ' ', regex=True)

In [ ]:
import re
mat_softys.Codigo_Barras_Bolsa = mat_softys.Codigo_Barras_Bolsa.astype(str)
mat_softys.Codigo_Barras_Caja = mat_softys.Codigo_Barras_Caja.astype(str)

mat_softys.Codigo_Barras_Bolsa = [re.sub("^0+", "", ele) for ele in mat_softys.Codigo_Barras_Bolsa]
mat_softys.Codigo_Barras_Caja = [re.sub("^0+", "", ele) for ele in mat_softys.Codigo_Barras_Caja]


#mat_softys=mat_softys.iloc[:,[0,1,7,8,12,13]]

#mat_softys.columns.values[0] = "item_softys"

mat_softys = mat_softys.drop_duplicates(subset="Codigo_Barras_Caja", inplace=False)
mat_softys = mat_softys.drop_duplicates(subset="Codigo_Barras_Bolsa", inplace=False)

In [ ]:
# condicion a cumplir
condition = (mat_softys['Bolsas_X_Caja'] == "Material") | \
            (mat_softys['Piezas_X_Bolsa'] == "Material") | \
            (mat_softys['Bolsas_X_Caja'] == 0) | \
            (mat_softys['Piezas_X_Bolsa'] == 0)

# Delete rows based on the condition
mat_softys = mat_softys[~condition]

Separar el dataset y convertir el codigo de barras en un solo atributo

In [ ]:
# bolsa

mat_softys_bolsa=mat_softys[["Item1","Description","Bolsas_X_Caja", "Piezas_X_Bolsa", "Codigo_Barras_Bolsa"]]

mat_softys_bolsa["KEY_UPC_softys"] = mat_softys_bolsa["Codigo_Barras_Bolsa"].astype(str) + mat_softys_bolsa["Piezas_X_Bolsa"].astype(str) + mat_softys_bolsa["Bolsas_X_Caja"].astype(str)

mat_softys_bolsa=mat_softys_bolsa.drop_duplicates(subset=["KEY_UPC_softys"])

mat_softys_bolsa=mat_softys_bolsa.iloc[:,[0,5]]

# caja

mat_softys_caja=mat_softys[["Item1","Description","Bolsas_X_Caja", "Piezas_X_Bolsa", "Codigo_Barras_Caja"]]

mat_softys_caja["KEY_UPC_softys"] = mat_softys_caja["Codigo_Barras_Caja"].astype(str) + mat_softys_caja["Piezas_X_Bolsa"].astype(str) + mat_softys_caja["Bolsas_X_Caja"].astype(str)

mat_softys_caja=mat_softys_caja.drop_duplicates(subset=["KEY_UPC_softys"])

mat_softys_caja=mat_softys_caja.iloc[:,[0,5]]

/tmp/ipython-input-1265355574.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mat_softys_bolsa["KEY_UPC_softys"] = mat_softys_bolsa["Codigo_Barras_Bolsa"].astype(str) + mat_softys_bolsa["Piezas_X_Bolsa"].astype(str) + mat_softys_bolsa["Bolsas_X_Caja"].astype(str)
/tmp/ipython-input-1265355574.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mat_softys_caja["KEY_UPC_softys"] = mat_softys_caja["Codigo_Barras_Caja"].astype(str) + mat_softys_caja["Piezas_X_Bolsa"].astype(str) + mat_softys_caja["Bolsas_X_Caja"].astype(str)

Unir los dos dataset en uno mismo

In [ ]:
mat_softys=pd.concat([mat_softys_bolsa,mat_softys_caja],axis=0)

mat_softys.tail()

            Item1         KEY_UPC_softys
12833  3134141460  1001311703379014.06.0
12835  3515553040  1001311703399830.04.0
12836  3515553441  1001311703397434.04.0
12837  3515563040  1001311703400130.04.0
12838  3515563441  1001311703398134.04.0

#Historico

Los reportes estan en tabla de contigencia, por lo que solo se procede a realizar el proceso de seleccion de columnas para su carga
1.   Citerios de venta: sin valores faltantes
2.   AB: sin valores faltantes (yo actualizo el catalogo de productos previamente)
3.   **Locales:** revisar qué tipo de locales me hacen falta en mi catalogo general

In [ ]:
# TS & PC: casa vargas, coma, duero, la soledad, mini abastos,
df=pd.read_excel("/content/drive/MyDrive/Sell Out/Dbyte_cubos/Softys Diario-Semanal Sell Out.xlsx",
                 engine="openpyxl")

# eliminar las primeras (espacios de filtros y encabezados)
df = df.iloc[9:].copy()

# rename columns
df.columns.values[0] = "fecha"
df.columns.values[1] = "Cadena"
df.columns.values[2] = "ID_Local"
df.columns.values[3] = "nom_tienda"
df.columns.values[4] = "item_cadena"
df.columns.values[5] = "sku_softys"
df.columns.values[6] = "material"
df.columns.values[7] = "Cjas_Blts"
df.columns.values[8] = "Inv_cjas"
df.columns.values[9] = "importe_c/iva"

df.head(5)

,fecha,Cadena,ID_Local,nom_tienda,item_cadena,sku_softys,material,Cjas_Blts,Inv_cjas,importe_c/iva,Unnamed: 10
9,01/03/2025,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247331560,AB10331560,Papel Higienico Premier 600 Hd (1 Pq / Cja 10),0,0.2,0,65.39
10,01/03/2025,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247332666,AB11332666,Elite Ultra Suave 4R 220Hd 4Pz (1 Pz / Cja 12),0,1,0,206.9
11,01/03/2025,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247335226,AB11335223,Toalla De Papel Elite 180H (1 Pz / Cja 20),0.3,7.55,98.79,2291.88
12,01/03/2025,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247338583,AB17335636,Papel Big Roll 550Hd 6R (1 Pq / Cja 48),1.63,34.58,526.47,12018.97
13,01/03/2025,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),27502247331468,AB11331461,Papel Higienico Premier Mega 4 (1 Pq / Blt 40),1.05,8.35,218.71,1854.37

# Arreglos

**Cambiar tipo de valores**

In [ ]:
so = df.copy()

# quitar ultima columna
so.drop(so.columns[-1], axis=1, inplace=True)

# quitar espacios en blanco
so = so.replace(r'\s+', ' ', regex=True)

# quitar los zeros de izquierda en identificadores de tienda
so['ID_Local'] = so['ID_Local'].astype(str).str.lstrip('0')

so.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145565 entries, 9 to 145573
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   fecha          145565 non-null  object
 1   Cadena         145565 non-null  object
 2   ID_Local       145565 non-null  object
 3   nom_tienda     145565 non-null  object
 4   item_cadena    145565 non-null  object
 5   sku_softys     145565 non-null  object
 6   material       145553 non-null  object
 7   Cjas_Blts      145565 non-null  float64
 8   Inv_cjas       145565 non-null  float64
 9   importe_c/iva  145565 non-null  float64
dtypes: float64(3), object(7)
memory usage: 11.1+ MB

/tmp/ipython-input-1687763531.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  so = so.replace(r'\s+', ' ', regex=True)

In [ ]:
# identificadores
so['ID_Local']=so['ID_Local'].astype(object)

so['sku_softys']=so['sku_softys'].astype(object)

# cuando es .CSV, es necesario quitar caracteres especiales antes de declarar el valor en decimales
so['Cjas_Blts'] = so['Cjas_Blts'].astype(str)
#so['Cjas_Blts'] = so['Cjas_Blts'].str.replace(' - ', '0.0', regex=False)
#so['Cjas_Blts'] = so['Cjas_Blts'].str.replace(',', '', regex=False)
so['Cjas_Blts']=so['Cjas_Blts'].astype(np.float64)

so['Inv_cjas'] = so['Inv_cjas'].astype(str)
#so['Inv_cjas'] = so['Inv_cjas'].str.replace(' - ', '0.0', regex=False)
#so['Inv_cjas'] = so['Inv_cjas'].str.replace(',', '', regex=False)
so["Inv_cjas"]=so['Inv_cjas'].astype(np.float64)

so['importe_c/iva'] = so['importe_c/iva'].astype(str)
#so['importe_c/iva'] = so['importe_c/iva'].str.replace(' - ', '0.0', regex=False)
#so['importe_c/iva'] = so['importe_c/iva'].str.replace(',', '', regex=False)
so['importe_c/iva']=so['importe_c/iva'].astype(np.float64)

---- Inicia división de Base de datos: inventarios y ventas-----

Inventarios reportados

In [ ]:
# dividir data set Inventarios vs Ventas
inventario = so.copy()
inventario = inventario.iloc[:,[0,1,2,3,4,5,6,8]]

# filtrar fechas
inventario['fecha'] = pd.to_datetime(inventario['fecha'], format='mixed', dayfirst=True)

In [ ]:
list(inventario['fecha'].unique())

[Timestamp('2025-03-01 00:00:00'),
 Timestamp('2025-03-02 00:00:00'),
 Timestamp('2025-03-03 00:00:00'),
 Timestamp('2025-03-04 00:00:00'),
 Timestamp('2025-03-05 00:00:00'),
 Timestamp('2025-03-06 00:00:00'),
 Timestamp('2025-03-07 00:00:00'),
 Timestamp('2025-03-08 00:00:00'),
 Timestamp('2025-03-09 00:00:00'),
 Timestamp('2025-03-10 00:00:00'),
 Timestamp('2025-03-11 00:00:00'),
 Timestamp('2025-03-12 00:00:00'),
 Timestamp('2025-03-13 00:00:00'),
 Timestamp('2025-03-14 00:00:00'),
 Timestamp('2025-03-15 00:00:00'),
 Timestamp('2025-03-16 00:00:00'),
 Timestamp('2025-03-17 00:00:00'),
 Timestamp('2025-03-18 00:00:00'),
 Timestamp('2025-03-19 00:00:00'),
 Timestamp('2025-03-20 00:00:00'),
 Timestamp('2025-03-21 00:00:00'),
 Timestamp('2025-03-22 00:00:00'),
 Timestamp('2025-03-23 00:00:00'),
 Timestamp('2025-03-24 00:00:00'),
 Timestamp('2025-03-25 00:00:00'),
 Timestamp('2025-03-26 00:00:00'),
 Timestamp('2025-03-27 00:00:00'),
 Timestamp('2025-03-28 00:00:00'),
 Timestamp('2025-03-29 00:00:00'),
 Timestamp('2025-03-30 00:00:00'),
 Timestamp('2025-03-31 00:00:00'),
 Timestamp('2025-04-01 00:00:00'),
 Timestamp('2025-04-02 00:00:00'),
 Timestamp('2025-04-03 00:00:00'),
 Timestamp('2025-04-04 00:00:00'),
 Timestamp('2025-04-05 00:00:00'),
 Timestamp('2025-04-06 00:00:00'),
 Timestamp('2025-04-07 00:00:00'),
 Timestamp('2025-04-08 00:00:00'),
 Timestamp('2025-04-09 00:00:00'),
 Timestamp('2025-04-10 00:00:00'),
 Timestamp('2025-04-11 00:00:00'),
 Timestamp('2025-04-12 00:00:00'),
 Timestamp('2025-04-13 00:00:00'),
 Timestamp('2025-04-14 00:00:00'),
 Timestamp('2025-04-15 00:00:00'),
 Timestamp('2025-04-16 00:00:00'),
 Timestamp('2025-04-17 00:00:00'),
 Timestamp('2025-04-18 00:00:00'),
 Timestamp('2025-04-19 00:00:00'),
 Timestamp('2025-04-20 00:00:00'),
 Timestamp('2025-04-21 00:00:00'),
 Timestamp('2025-04-22 00:00:00'),
 Timestamp('2025-04-23 00:00:00'),
 Timestamp('2025-04-24 00:00:00'),
 Timestamp('2025-04-25 00:00:00'),
 Timestamp('2025-04-26 00:00:00'),
 Timestamp('2025-04-27 00:00:00'),
 Timestamp('2025-04-28 00:00:00'),
 Timestamp('2025-04-29 00:00:00'),
 Timestamp('2025-04-30 00:00:00'),
 Timestamp('2025-05-01 00:00:00'),
 Timestamp('2025-05-02 00:00:00'),
 Timestamp('2025-05-03 00:00:00'),
 Timestamp('2025-05-04 00:00:00'),
 Timestamp('2025-05-05 00:00:00'),
 Timestamp('2025-05-06 00:00:00'),
 Timestamp('2025-05-07 00:00:00'),
 Timestamp('2025-05-08 00:00:00'),
 Timestamp('2025-05-09 00:00:00'),
 Timestamp('2025-05-10 00:00:00'),
 Timestamp('2025-05-11 00:00:00'),
 Timestamp('2025-05-12 00:00:00'),
 Timestamp('2025-05-13 00:00:00'),
 Timestamp('2025-05-14 00:00:00'),
 Timestamp('2025-05-15 00:00:00'),
 Timestamp('2025-05-16 00:00:00'),
 Timestamp('2025-05-17 00:00:00'),
 Timestamp('2025-05-18 00:00:00'),
 Timestamp('2025-05-19 00:00:00'),
 Timestamp('2025-05-20 00:00:00'),
 Timestamp('2025-05-21 00:00:00'),
 Timestamp('2025-05-22 00:00:00'),
 Timestamp('2025-05-23 00:00:00'),
 Timestamp('2025-05-24 00:00:00'),
 Timestamp('2025-05-25 00:00:00'),
 Timestamp('2025-05-26 00:00:00'),
 Timestamp('2025-05-27 00:00:00'),
 Timestamp('2025-05-28 00:00:00'),
 Timestamp('2025-05-29 00:00:00'),
 Timestamp('2025-05-30 00:00:00'),
 Timestamp('2025-05-31 00:00:00'),
 Timestamp('2025-06-01 00:00:00'),
 Timestamp('2025-06-02 00:00:00'),
 Timestamp('2025-06-03 00:00:00'),
 Timestamp('2025-06-04 00:00:00'),
 Timestamp('2025-06-05 00:00:00'),
 Timestamp('2025-06-06 00:00:00'),
 Timestamp('2025-06-07 00:00:00'),
 Timestamp('2025-06-08 00:00:00'),
 Timestamp('2025-06-09 00:00:00'),
 Timestamp('2025-06-10 00:00:00'),
 Timestamp('2025-06-11 00:00:00'),
 Timestamp('2025-06-12 00:00:00'),
 Timestamp('2025-06-13 00:00:00'),
 Timestamp('2025-06-14 00:00:00'),
 Timestamp('2025-06-15 00:00:00'),
 Timestamp('2025-06-16 00:00:00'),
 Timestamp('2025-06-17 00:00:00'),
 Timestamp('2025-06-18 00:00:00'),
 Timestamp('2025-06-19 00:00:00'),
 Timestamp('2025-06-20 00:00:00'),
 Timestamp('2025-06-21 00:00:00'),
 Timestamp('2025-06-22 00:00:00'),
 Timestamp('2025-06-23 00:00:00'),
 Timestamp('2025-06-24 00:00:00'),
 Timestamp('2025-06-25 00:00:00'),
 Timestamp('2025-06-26 00:00:00'),
 Timestamp('2025-06-27 00:00:00'),
 Timestamp('2025-06-28 00:00:00'),
 Timestamp('2025-06-29 00:00:00'),
 Timestamp('2025-06-30 00:00:00'),
 Timestamp('2025-07-01 00:00:00'),
 Timestamp('2025-07-02 00:00:00'),
 Timestamp('2025-07-03 00:00:00'),
 Timestamp('2025-07-04 00:00:00'),
 Timestamp('2025-07-05 00:00:00'),
 Timestamp('2025-07-06 00:00:00'),
 Timestamp('2025-07-07 00:00:00'),
 Timestamp('2025-07-08 00:00:00'),
 Timestamp('2025-07-09 00:00:00'),
 Timestamp('2025-07-10 00:00:00'),
 Timestamp('2025-07-11 00:00:00'),
 Timestamp('2025-07-12 00:00:00'),
 Timestamp('2025-07-13 00:00:00'),
 Timestamp('2025-07-14 00:00:00'),
 Timestamp('2025-07-15 00:00:00'),
 Timestamp('2025-07-16 00:00:00'),
 Timestamp('2025-07-17 00:00:00'),
 Timestamp('2025-07-18 00:00:00'),
 Timestamp('2025-07-19 00:00:00'),
 Timestamp('2025-07-20 00:00:00'),
 Timestamp('2025-07-21 00:00:00'),
 Timestamp('2025-07-22 00:00:00'),
 Timestamp('2025-07-23 00:00:00'),
 Timestamp('2025-07-24 00:00:00'),
 Timestamp('2025-07-25 00:00:00'),
 Timestamp('2025-07-26 00:00:00'),
 Timestamp('2025-07-27 00:00:00'),
 Timestamp('2025-07-28 00:00:00'),
 Timestamp('2025-07-29 00:00:00'),
 Timestamp('2025-07-30 00:00:00'),
 Timestamp('2025-07-31 00:00:00'),
 Timestamp('2025-08-01 00:00:00'),
 Timestamp('2025-08-02 00:00:00'),
 Timestamp('2025-08-03 00:00:00'),
 Timestamp('2025-08-04 00:00:00'),
 Timestamp('2025-08-05 00:00:00'),
 Timestamp('2025-08-06 00:00:00'),
 Timestamp('2025-08-07 00:00:00'),
 Timestamp('2025-08-08 00:00:00'),
 Timestamp('2025-08-09 00:00:00'),
 Timestamp('2025-08-10 00:00:00'),
 Timestamp('2025-08-11 00:00:00'),
 Timestamp('2025-08-12 00:00:00'),
 Timestamp('2025-08-13 00:00:00'),
 Timestamp('2025-08-14 00:00:00'),
 Timestamp('2025-08-15 00:00:00'),
 Timestamp('2025-08-16 00:00:00'),
 Timestamp('2025-08-17 00:00:00'),
 Timestamp('2025-08-18 00:00:00'),
 Timestamp('2025-08-19 00:00:00'),
 Timestamp('2025-08-20 00:00:00'),
 Timestamp('2025-08-21 00:00:00'),
 Timestamp('2025-08-22 00:00:00'),
 Timestamp('2025-08-23 00:00:00'),
 Timestamp('2025-08-24 00:00:00'),
 Timestamp('2025-08-25 00:00:00'),
 Timestamp('2025-08-26 00:00:00'),
 Timestamp('2025-08-27 00:00:00'),
 Timestamp('2025-08-28 00:00:00'),
 Timestamp('2025-08-29 00:00:00'),
 Timestamp('2025-08-30 00:00:00'),
 Timestamp('2025-08-31 00:00:00'),
 Timestamp('2025-09-01 00:00:00'),
 Timestamp('2025-09-02 00:00:00'),
 Timestamp('2025-09-03 00:00:00'),
 Timestamp('2025-09-04 00:00:00'),
 Timestamp('2025-09-05 00:00:00'),
 Timestamp('2025-09-06 00:00:00'),
 Timestamp('2025-09-07 00:00:00'),
 Timestamp('2025-09-08 00:00:00'),
 Timestamp('2025-09-09 00:00:00'),
 Timestamp('2025-09-10 00:00:00'),
 Timestamp('2025-09-11 00:00:00'),
 Timestamp('2025-09-12 00:00:00'),
 Timestamp('2025-09-13 00:00:00'),
 Timestamp('2025-09-14 00:00:00'),
 Timestamp('2025-09-15 00:00:00'),
 Timestamp('2025-09-16 00:00:00'),
 Timestamp('2025-09-17 00:00:00')]

In [ ]:
specific_dates = [ '2025-04-06 00:00:00', '2025-04-13 00:00:00', '2025-04-20 00:00:00', '2025-04-27 00:00:00',
    '2025-05-04 00:00:00',"2025-05-11 00:00:00","2025-05-18 00:00:00","2025-05-25 00:00:00",
                  "2025-06-01 00:00:00", "2025-06-08 00:00:00", "2025-06-15 00:00:00","2025-06-22 00:00:00","2025-06-29 00:00:00",
                  "2025-07-06 00:00:00", "2025-07-13 00:00:00", "2025-07-20 00:00:00", "2025-07-27 00:00:00",
                  "2025-08-03 00:00:00", "2025-08-10 00:00:00", "2025-08-17 00:00:00", "2025-08-24 00:00:00", "2025-08-31 00:00:00",
                  "2025-09-07 00:00:00", "2025-09-14 00:00:00"
 ]
inventario = inventario[inventario['fecha'].isin(pd.to_datetime(specific_dates))]

Ventas rportadas

In [ ]:
ventas = so.iloc[:,[0,1,2,3,4,5,6,7,9]]

# formato de fecha
ventas['fecha'] = pd.to_datetime(ventas['fecha'], format='mixed', dayfirst=True)

/tmp/ipython-input-1365589246.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['fecha'] = pd.to_datetime(ventas['fecha'], format='mixed', dayfirst=True)

In [ ]:
# paste inventario below of so data frame
so_combined = pd.concat([ventas, inventario], axis=0)

# fill nas with zeros
so_combined= so_combined.fillna(0)

so = so_combined.copy()
so.head(5)

,fecha,Cadena,ID_Local,nom_tienda,item_cadena,sku_softys,material,Cjas_Blts,importe_c/iva,Inv_cjas
9,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247331560,AB10331560,Papel Higienico Premier 600 Hd (1 Pq / Cja 10),0.00,0.00,0.0
10,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247332666,AB11332666,Elite Ultra Suave 4R 220Hd 4Pz (1 Pz / Cja 12),0.00,0.00,0.0
11,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247335226,AB11335223,Toalla De Papel Elite 180H (1 Pz / Cja 20),0.30,98.79,0.0
12,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247338583,AB17335636,Papel Big Roll 550Hd 6R (1 Pq / Cja 48),1.63,526.47,0.0
13,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),27502247331468,AB11331461,Papel Higienico Premier Mega 4 (1 Pq / Blt 40),1.05,218.71,0.0

--- Fin del proceso: union de bases ---

**Fecha**

1. Fecha a nivel semanal con formato calendario

formato de la columna fecha cuando se encuentra en su forma estandar (dada por default)

In [ ]:
so['fecha'] = pd.to_datetime(so['fecha'], format='mixed', dayfirst=True)

Agrupar registros diarios conforme al ultimo dia de semana (ISO), para asi obtener el corte de venta a nivel semana

In [8]:
# tabla calendario
calendario = pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Calender_Softy_SO.xlsx",
                 sheet_name="Calendario",
                 engine="openpyxl")

calendario.head(5)

,Año,Mes,Sem_año_default,# semana_default,# semana softy,Trimestre,Ultimo dia de la semana
0,2021,Enero,2021-01-01,1,0,1,2021-01-03
1,2021,Enero,2021-01-02,1,0,1,2021-01-03
2,2021,Enero,2021-01-03,1,0,1,2021-01-03
3,2021,Enero,2021-01-04,2,1,1,2021-01-10
4,2021,Enero,2021-01-05,2,1,1,2021-01-10

In [9]:
calendario= calendario.iloc[:,[2,6]]

calendario.columns.values[0]= "fecha"
calendario.columns.values[1]= "fecha BI"

In [ ]:
# ultimo dia de semana de los días consecutivos = fecha de cierre semanal
so = so.merge(calendario, left_on="fecha", right_on="fecha", how="left")
so.head(2)

,fecha,Cadena,ID_Local,nom_tienda,item_cadena,sku_softys,material,Cjas_Blts,importe_c/iva,Inv_cjas,fecha BI
0,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247331560,AB10331560,Papel Higienico Premier 600 Hd (1 Pq / Cja 10),0.0,0.0,0.0,2025-03-02
1,2025-03-01,Mas Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247332666,AB11332666,Elite Ultra Suave 4R 220Hd 4Pz (1 Pz / Cja 12),0.0,0.0,0.0,2025-03-02

In [ ]:
#rango de fechas en caso de agrupar pocas observaciones
#start_date = datetime.strptime('04/28/2025', '%m/%d/%Y')
#end_date = datetime.strptime('05/04/2025', '%m/%d/%Y')

#filtrar el rango de fechas dadas
#so = so[(so['fecha'] >= start_date) & (so['fecha'] <=end_date)]

2. Fecha a nivel mes, que necesita ser trasnformado a formato calendario

In [ ]:
so['fecha'].unique()

<DatetimeArray>
['2025-03-01 00:00:00', '2025-03-02 00:00:00', '2025-03-03 00:00:00',
 '2025-03-04 00:00:00', '2025-03-05 00:00:00', '2025-03-06 00:00:00',
 '2025-03-07 00:00:00', '2025-03-08 00:00:00', '2025-03-09 00:00:00',
 '2025-03-10 00:00:00',
 ...
 '2025-09-08 00:00:00', '2025-09-09 00:00:00', '2025-09-10 00:00:00',
 '2025-09-11 00:00:00', '2025-09-12 00:00:00', '2025-09-13 00:00:00',
 '2025-09-14 00:00:00', '2025-09-15 00:00:00', '2025-09-16 00:00:00',
 '2025-09-17 00:00:00']
Length: 201, dtype: datetime64[ns]

In [ ]:
# caracter de fecha a fecha cardinal
so['fecha'] = so['fecha'].replace({
    '01 Ene': '1/1/2025',
    '02 Feb': '1/2/2025',
    '03 Mar': '1/3/2025',
    '04 Abr': '1/4/2025',
    '05 May': '1/5/2025',
    '06 Jun': '1/6/2025'
})

# formato de la columna fecha cuando se encuentra en su forma estandar (dada por default)
so['fecha'] = pd.to_datetime(so['fecha'], format='mixed', dayfirst=True)

**Homologar nombre de cadenas**

In [ ]:
so['Cadena'].unique()

array(['Mas Bodega'], dtype=object)

In [ ]:
# rename varios objetos en la columna
so['Cadena'] = so['Cadena'].replace({
    "Abarrotes Rivera":'Gran Bodega',
    "Consumo Z":'PCZ',
    'Mas Bodega':'Más Bodega',
    "Parral":'Abastecedora Parral',
    "Abarrotera Duero": "Duero",
    "Sanchez": "Grupo Sanchez",
    "Decasa": "DECASA",
    "Abarrotera Del Norte": "Promotora Abarrotera del Norte",
    "Coma": "COMA",
    "Abarrotes Soledad": "La Soledad",
    "San Francisco de Asis": "Super Aki"
    })

In [ ]:
so["sku_softys"].unique()

array(['AB10331560', 'AB11332666', 'AB11335223', 'AB17335636',
       'AB11331461', 'AB12332659', 'AB11332826', 'AB10332987',
       'AB12335445', 'AB14101664', 'AB16000852', 'AB15090074',
       'AB40331836', 'AB22090011', 'AB14335678', 'AB40331850',
       'AB40331867', 'AB12330570', 'AB11332468', 'AB13700228',
       'UPC Nuevo 17502247333106', 'UPC Nuevo 17502279701072'],
      dtype=object)

Crear una key de mi dataset

In [ ]:
so['keytda'] =so['Cadena'].astype(str) + so['ID_Local'].astype(str)

Espacios y negativos: valores con 0

In [ ]:
# iterar sobre toda las columnas numericas
cols = so.select_dtypes(include='number').columns
so[cols] = so[cols].mask(so[cols] < 0)

# rellenar con 0 los espacios en blanco en todo el dataset
so = so.fillna(0)

# conteo de espacios en blanco
total_nan_count = so.isna().sum().sum()
print("Total NaN count in DataFrame:", total_nan_count)

Total NaN count in DataFrame: 0

# Calidad de los Datos

Realizar una variable que permita identificar la anomalias de los datos

In [ ]:
so.head(2)

,fecha,Cadena,ID_Local,nom_tienda,item_cadena,sku_softys,material,Cjas_Blts,importe_c/iva,Inv_cjas,fecha BI,keytda
0,2025-04-01,Más Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247331560,AB10331560,Papel Higienico Premier 600 Hd (1 Pq / Cja 10),0.0,0.0,0.0,2025-04-06,Más Bodega10
1,2025-04-01,Más Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247332666,AB11332666,Elite Ultra Suave 4R 220Hd 4Pz (1 Pz / Cja 12),0.0,0.0,0.0,2025-04-06,Más Bodega10

In [ ]:
# columnas seleccionadas por index
out=so.iloc[:,[1,7,9]]

# solo seleccionar valores con registros mayores que cero en ambos atributos
out = out[(out['Cjas_Blts']>0) & (out['importe_c/iva']>0)]

In [ ]:
out["precio_unidad"]= out['importe_c/iva'] / out["Cjas_Blts"]

IQR

In [ ]:
# Perentiles
seventy_fifth = out["precio_unidad"].quantile(0.75)
twenty_fifth = out["precio_unidad"].quantile(0.25)

# Obtener IQR
iqr = seventy_fifth - twenty_fifth

# Upper and lower thresholds
upper = seventy_fifth + (0.5 * iqr)
lower = twenty_fifth - (0.5 * iqr)

# Subset the dataset
outliers = out[(out["precio_unidad"] < lower) | (out["precio_unidad"] > upper)]
outliers.head()

# Obtain number of outliers
print(f'Number of outliers: {len(outliers)}')

In [ ]:
round(out['precio_unidad'].groupby(out['Cadena']).
      describe(),3)

In [ ]:
# Histograma rapido, pero no estetico
histogramas = out['precio_unidad'].hist(by=out['Cadena'])

In [ ]:
# exportar los outliers
outliers.to_excel('out.xlsx',sheet_name = 'Sheet1',index=False)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Replace infinite values with NaN
out.replace([np.inf, -np.inf], np.nan, inplace=True)

# Drop rows with NaN values in 'precio_unidad' column
out.dropna(subset=['precio_unidad'], inplace=True)

# Calculate the number of unique 'Cadena' values
num_cadenas = len(out['Cadena'].unique())

# Calculate the number of rows and columns for subplots
# Adjust nrows and ncols as needed to accommodate all 'Cadena' values
nrows = int(np.ceil(num_cadenas / 3))  # Example: 3 columns
ncols = 3

# Create the figure and axes with enough subplots
fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(12, 4*nrows))

# Flatten the axes array if necessary
axes = axes.flatten()

# Loop through unique 'Cadena' values and create histograms
for i, cadena in enumerate(out['Cadena'].unique()):
    # Select data for the current 'Cadena'
    cadena_data = out[out['Cadena'] == cadena]['precio_unidad']

    # Plot histogram on the corresponding axes
    axes[i].hist(cadena_data)
    axes[i].set_title(cadena)  # Set title for each subplot

# Hide any empty subplots if num_cadenas is not a multiple of nrows*ncols
for i in range(num_cadenas, nrows * ncols):
    axes[i].set_visible(False)

plt.tight_layout()
plt.show()

# Merge

**Espacios en blanco**

In [ ]:
# espacios en blanco para todo los archivos a trabajar

so = so.replace(r'\s+', ' ', regex=True)

tdas = tdas.replace(r'\s+', ' ', regex=True)

ab = ab.replace(r'\s+', ' ', regex=True)

## Merge 1: Tiendas

**ELIMINAR tiendas o REMPLAZAR el registro de Tiendas**

In [ ]:
# Duero
so["ID_Local"] = so["ID_Local"].replace(["C004"], "C354")

##########################
# Garis
condition =(so["ID_Local"] == "E3") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "E5") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "F2") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "GB") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "BOD") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "CUM") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "LOT") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "MER") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "PAB") & (so["Cadena"] == "Garis") | \
           (so["ID_Local"] == "CUL") & (so["Cadena"] == "Garis")
#Delete rows based on the condition
so = so[~condition]

#############################
# Zorro
condition =(so["ID_Local"] == "CED") & (so["Cadena"] == "Zorro") | \
           (so["ID_Local"] == "DLS") & (so["Cadena"] == "Zorro") | \
           (so["ID_Local"] == "CPI") & (so["Cadena"] == "Zorro")
so = so[~condition]

################################
# Sanchez
condition =(so["ID_Local"] == "VENTA EXPO") & (so["Cadena"] == "Grupo Sanchez")
condition =(so["ID_Local"] == "BODEGA LOGISTICA INVERSA") & (so["Cadena"] == "Grupo Sanchez")

so = so[~condition]

##############################
# Aki
condition =(so["ID_Local"] == "31") & (so["Cadena"] == "Super Aki")
so = so[~condition]

so.loc[(so["ID_Local"] == "127") & (so["Cadena"] == "Super Aki"), "ID_Local"] = "127"

####################################
# Gran Bodega
so.loc[(so["ID_Local"] == "83") & (so["Cadena"] == "Gran Bodega"), "ID_Local"] = "83 IZUCAR"

#################################
# PCZ
#eliminar los siguientes puntos de venta
condition =(so["ID_Local"] == 603) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 251) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 902) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 602) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 500) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 284) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 862) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 2) & (so["Cadena"] == "PCZ")   | \
           (so["ID_Local"] == 922) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 792) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 942) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 842) & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == "200-Id") & (so["Cadena"] == "PCZ") | \
           (so["ID_Local"] == 822) & (so["Cadena"] == "PCZ")
# Delete rows based on the condition
so = so[~condition]

# sustitucion de tienda
so.loc[(so["ID_Local"] == "827") & (so["Cadena"] == "PCZ"), "ID_Local"] = "487"
so.loc[(so["ID_Local"] == "832") & (so["Cadena"] == "PCZ"), "ID_Local"] = "831"

######################################
# Sahuayo
so.loc[(so["ID_Local"] == "12") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "11"
so.loc[(so["ID_Local"] == "12603") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "49"
so.loc[(so["ID_Local"] == "13") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "9"
so.loc[(so["ID_Local"] == "16") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "102"
so.loc[(so["ID_Local"] == "17") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "63"
so.loc[(so["ID_Local"] == "21") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "18"
so.loc[(so["ID_Local"] == "22") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "19"
so.loc[(so["ID_Local"] == "23") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "84"
so.loc[(so["ID_Local"] == "25") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "51"
so.loc[(so["ID_Local"] == "27") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "24"
so.loc[(so["ID_Local"] == "31") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "15"
so.loc[(so["ID_Local"] == "32") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "69"
so.loc[(so["ID_Local"] == "34") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "33"
so.loc[(so["ID_Local"] == "38") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "36"
so.loc[(so["ID_Local"] == "41") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "42"
so.loc[(so["ID_Local"] == "5") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "26"
so.loc[(so["ID_Local"] == "7") & (so["Cadena"] == "Sahuayo"), "ID_Local"] = "58"

###########################
#CAGSA
condition =(so["ID_Local"] == 285827) & (so["Cadena"] == "CAGSA")
so = so[~condition]

###########################
# Parral
so.loc[(so["ID_Local"] == "") & (so["nom_tienda"] == "ACP CHH CEDIS"), "ID_Local"] = "1"

**Tiendas Dbyte >> Tiendas relacionadas**

In [ ]:
# catalogo de tiendas relacionadas
tdas_dbyte=pd.read_excel("/content/drive/MyDrive/Sell Out/Dbyte_cubos/RelTdas_Dbyte.xlsx")
tdas_dbyte = tdas_dbyte.replace(r'\s+', ' ', regex=True)

In [ ]:
# renombrar columnas en catalogo de tiendas dbyte
tdas_dbyte= tdas_dbyte.rename(columns={'Cadena': "Holding"})
tdas_dbyte= tdas_dbyte.rename(columns={'ID_Original': "Código Punto de Venta Cadena"})
tdas_dbyte= tdas_dbyte.rename(columns={'nombre_local': "Nombre de Tienda"})

# Key Tda
tdas_dbyte['key_tda'] =tdas_dbyte['Holding'].astype(str) + tdas_dbyte['ID_local'].astype(str)

# seleccionar columnas
tdas_dbyte= tdas_dbyte.iloc[:,[3,4]]

# reacomodar columnas
tdas_dbyte = tdas_dbyte.iloc[:, [1,0]]

*Diccionario de cambios:*
1.   Tiendas relacionadas para Dbyte
2.   Tiendas relacionadas deben de aparejarse con las tiendas reportadas en sell out
3.  Una vez aparejadas, se debe retomar el codigo de punto original que reporta la cadena

In [ ]:
so['ID_Local'] = so['ID_Local'].astype(str)
tdas_dbyte['key_tda'] = tdas_dbyte['key_tda'].astype(str)

# Create a dictionary mapping 'key_tda' (tdas_dbyte) to 'Código Punto de Venta Cadena' (so)
replacement_dict = dict(zip(tdas_dbyte['key_tda'], tdas_dbyte['Código Punto de Venta Cadena']))

# Use the dictionary to replace values in 'so'
so['ID_Local'] = so['keytda'].map(replacement_dict).fillna(so['ID_Local'])

**Tiendas relacionadas >> Catalogo de tiendas BI**

In [ ]:
# reformar de nuevo la columna key_tda (referenciar a catalogos de tienda) sobre la ya realizada
so['keytda'] =so['Cadena'].astype(str) + so['ID_Local'].astype(str)

# merge
so = so.merge(tdas, left_on="keytda", right_on="key_tda", how="left")

# eliminar descripciones "eliminar"
so = so[so['ID_Local'] != 'eliminar']

*Resultado = Tiendas no relacionadas*

In [ ]:
tdas_nas= so[so.isna().any(axis=1)]  #revisar registros con datos faltantes
tdas_nas.to_excel('tdas_nas.xlsx',sheet_name = 'Sheet1',index=False)

tdas_nas.tail()

#so.dropna(inplace=True) #eliminar registros con datos faltantes

Empty DataFrame
Columns: [fecha, Cadena, ID_Local, nom_tienda, item_cadena, sku_softys, material, Cjas_Blts, importe_c/iva, Inv_cjas, fecha BI, keytda, key_tda]
Index: []

## Merge 2: Productos

**Codigo cadena >> AB relacionado**

In [ ]:
prod_holding=pd.read_excel("/content/drive/MyDrive/Sell Out/Dbyte_cubos/Prod_Holding.xlsx",
                 engine="openpyxl")

prod_holding= prod_holding.iloc[:,[3,5]]

prod_holding = prod_holding.drop_duplicates()
prod_holding = prod_holding.dropna()

prod_holding = prod_holding.replace(r'\s+', ' ', regex=True)

prod_holding.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2640 entries, 0 to 3258
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   identificador  2640 non-null   object
 1   CODIGO         2640 non-null   object
dtypes: object(2)
memory usage: 61.9+ KB

In [ ]:
# igualar los tipos de atributos en tipo de datos para el Merge

prod_holding['identificador']=prod_holding['identificador'].astype(str)
so['item_cadena']=so['item_cadena'].astype(str)

In [ ]:
so = so.merge(prod_holding, left_on="item_cadena", right_on="identificador", how="left")

In [ ]:
prod_nas= so[so.isna().any(axis=1)]  #revisar registros con datos faltantes
prod_nas.to_excel('prod_nas.xlsx',sheet_name = 'Sheet1',index=False)

prod_nas.tail()
#so.dropna(inplace=True) #eliminar registros con datos faltantes

**AB relacionado >> Catalogo de materiales AB**

Realizar las transformaciones de paquetes a cajas, es decir, multiplicar la variable por el factor de paquetes-cajas

In [ ]:
so.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160160 entries, 0 to 160171
Data columns (total 15 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   fecha          160160 non-null  datetime64[ns]
 1   Cadena         160160 non-null  object
 2   ID_Local       160160 non-null  object
 3   nom_tienda     160160 non-null  object
 4   item_cadena    160160 non-null  object
 5   sku_softys     160160 non-null  object
 6   material       160160 non-null  object
 7   Cjas_Blts      160160 non-null  float64
 8   importe_c/iva  160160 non-null  float64
 9   Inv_cjas       160160 non-null  float64
 10  fecha BI       160160 non-null  datetime64[ns]
 11  keytda         160160 non-null  object
 12  key_tda        160160 non-null  object
 13  identificador  160160 non-null  object
 14  CODIGO         160160 non-null  object
dtypes: datetime64[ns](2), float64(3), object(10)
memory usage: 19.6+ MB

In [ ]:
# conservar columnas de trabajo
#so = so.iloc[:,[ ]]

# eliminar codigos sin regitros de prod_holding
so = so[so['CODIGO'] !='eliminar']

#######
# {factor cajas}
#so = so.merge(ab, left_on="CODIGO", right_on="CODIGO", how="left")

# Trasnformar piezas e inventarios (dbyte) a cajas
#so["Cjas_Blts"]= so['Cjas_Blts']/so['Empaquetado (Cj/Blt)']
#so["Inv_cjas"]= so['Inv_cjas']/so['Empaquetado (Cj/Blt)']
########

# importe sin iva
so["importe_s/iva"] = so['importe_c/iva']/1.16

so.head(1)

,fecha,Cadena,ID_Local,nom_tienda,item_cadena,sku_softys,material,Cjas_Blts,importe_c/iva,Inv_cjas,fecha BI,keytda,key_tda,identificador,CODIGO,importe_s/iva
0,2025-03-01,Más Bodega,10,10 Mas Bodega MAS-GPE (BENITO JUAREZ),17502247331560,AB10331560,Papel Higienico Premier 600 Hd (1 Pq / Cja 10),0.0,0.0,0.0,2025-03-02,Más Bodega10,Más Bodega10,17502247331560,AB10331560,0.0

# Layout BI

Renombras columnas en función del layout original

In [ ]:
# tabla de contigencia
pivot_table = pd.pivot_table(data= so,
                              index= [ "fecha BI","Cadena", "ID_Local", "CODIGO"], # fecha BI
                              values= ["Cjas_Blts", "Inv_cjas", "importe_c/iva", "importe_s/iva"],
                              aggfunc= np.sum,
                              fill_value=0,)

# drop observations when we have at least 0 in other attributes
pivot_table = pivot_table[~(pivot_table == 0).all(axis=1)]

# Assuming you want the current column order
column_order = ["fecha BI","Cadena", "ID_Local", "CODIGO","Cjas_Blts", "importe_s/iva", "Inv_cjas", "importe_c/iva"] # fecha BI

# exportar tabla contigencia
pivot_table.reset_index().to_excel('sell out.xlsx',sheet_name = 'Sheet1',index=False, columns= column_order)

/tmp/ipython-input-1610521325.py:2: FutureWarning: The provided callable <function sum at 0x7cd49b70b880> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_table = pd.pivot_table(data= so,