In [1]:
import glob
import pandas as pd

#Catalogos

##Materiales

1) Materiales Dbyte

In [8]:
# Materiales Dbyte
mat_dbyte=pd.read_excel('/content/drive/MyDrive/Sell Out/Dbyte_SO/Catalogo_Productos_SoftysSO.xlsx')

mat_dbyte=mat_dbyte.replace(r'\s+', ' ', regex=True)

mat_dbyte.head(5)

,Corporativo,Familia,Categoria,Marca,Sub_marca,Variedad_o_sabor,Empaque,Tipo,Status,Presentacion,...,Descripcion_No_Homologada_SKU,ID_UPC,Descripcion_Administracion,Numer_Categoria_SR,Categoria_SR,Prime_Item_Desc,Consumer_ID,Prime_Item_Nbr,Item_Soriana,Negocio
0,Ontex,Adultcare,Heavy Inco,Affective,Active,M MABESA,Adulto,Active,CONVENCIONAL,Grande,...,Panal Para Adulto AFFECTIVE Active Grande Paq 18u,137215,Adult Pants Affective Grande CA 4/18,-,-,-,-,-,-,Cuidado Adulto
1,Ontex,Adultcare,Heavy Inco,Affective,Active,M MABESA,Adulto,Active,CONVENCIONAL,Mediano,...,Panal Para Adulto AFFECTIVE Active Median Paq 20u,137530,Adult Pants Affective Mediano CA 4/20,-,-,-,-,-,-,Cuidado Adulto
2,Ontex,Adultcare,Heavy Inco,Affective,Active,M MABESA,Adulto,Active,CONVENCIONAL,T2,...,PANAL AD SAFE PANT S,43170,Adult Pants Affective Active Chica 6/12,-,-,AFFEC ACTIVE CH,190988639,100425325,-,Cuidado Adulto
3,Ontex,Adultcare,Heavy Inco,Affective,Active,M MABESA,Adulto,Active,CONVENCIONAL,T2,...,PANAL AD SAFE PANT S,42675,Affective Active Ropa Interior Desechable para...,-,-,AFFEC ACTIVE CH,190988639,100425325,-,Cuidado Adulto
4,Ontex,Adultcare,Heavy Inco,Affective,Active,M MABESA,Adulto,Active,CONVENCIONAL,T2,...,PANAL AD SAFE PANT S,43420,Affective Active Ropa Interior Desechable para...,-,-,-,-,-,-,Cuidado Adulto

In [9]:
import re

# selecting columns
mat_dbyte=mat_dbyte.iloc[:,[12,13,17,18]]

# renaming columns by index
#mat_dbyte.columns.values[0] = "desc_dbyte"
#mat_dbyte.columns.values[1] = "sku_dbyte"
#mat_dbyte.columns.values[2] = "ipc_dbyte"
#mat_dbyte.columns.values[3] = "grupo_dbyte"

# changue type of data
mat_dbyte['UPC'] = mat_dbyte['UPC'].astype(str)
mat_dbyte['UPC'] = [re.sub("^0+", "", ele) for ele in mat_dbyte['UPC']]

mat_dbyte['IPC'] = mat_dbyte['UPC'].astype(str)
mat_dbyte['IPC'] = [re.sub("^0+", "", ele) for ele in mat_dbyte['UPC']]

# drop duplicated with column of reference
mat_dbyte=mat_dbyte.drop_duplicates(subset=["IPC"])

mat_dbyte.head(5)

            UPC          IPC  Paquetes  Factor_cajas
0        247115       247115         4            18
1        247114       247114         4            20
2    1311702978   1311702978         6            12
10  13117029789  13117029789         6            12
14  13117032253  13117032253         4            20

Separa el dataset y crear un indentificador

In [ ]:
# TABLA DE UPC

# selecting columns
mat_dbyte_UPC=mat_dbyte[["UPC","Paquetes", "Factor_cajas"]]

# Key
mat_dbyte_UPC["KEY_UPC_dbyte"] = mat_dbyte_UPC["UPC"].astype(str) +  mat_dbyte_UPC["Factor_cajas"].astype(str) + mat_dbyte_UPC["Paquetes"].astype(str)

# drop duplicated Key
mat_dbyte_UPC=mat_dbyte_UPC.drop_duplicates(subset=["KEY_UPC_dbyte"])

# TABLA DE IPC

# selecting columns
mat_dbyte_IPC=mat_dbyte[["IPC","Paquetes", "Factor_cajas"]]

# Key
mat_dbyte_IPC["KEY_IPC_dbyte"] = mat_dbyte_IPC["IPC"].astype(str) +  mat_dbyte_IPC["Factor_cajas"].astype(str) + mat_dbyte_IPC["Paquetes"].astype(str)

# drop duplicated Key
mat_dbyte_IPC=mat_dbyte_IPC.drop_duplicates(subset=["KEY_IPC_dbyte"])


# unir vertical
#mat_dbyte=pd.concat([mat_dbyte_IPC,mat_dbyte_UPC],axis=0)

# Array de 2
UPC=mat_dbyte_UPC.iloc[:,[0,3]]
IPC=mat_dbyte_IPC.iloc[:,[0,3]]

2) Materiales Puebla

In [11]:
mat_softys=pd.read_excel('/content/drive/Shareddrives/Catalogos_SO/Catalogo_Puebla.xlsx')

# caracteres especiales
mat_softys=mat_softys.replace(r'\s+', ' ', regex=True)

mat_softys.head(5)

,Item1,Description,Division_Dsc,2_Marca_Dsc,1_Tipo_Dsc,4_Talla_Dsc,3_Acabado_Dsc,Bolsas_X_Caja,Piezas_X_Bolsa,Conteo1,...,Subcategoria,Boton_Negocio_002,Dm_Prod_Division_Producto_Desc,Dm_Prod_Segmento_Mercado_Desc,Dm_Prod_Segmento_Mercado,Dm_Prod_Categoria,Dm_Prod_Division_Producto,Avta_Sector_Desc,Dm_Prod_Subcategoria,Dm_Prod_Subcategoria_Desc
0,IF25650943,BABYLOVE GUTE-NACHT YPP LRG/XLRG 4/09'S,España,Baby Love Gute-Nacht,Calzon Entrenador,T5,Top,4.0,9.0,04/09,...,Pants infantil,PERSONAL CARE,Cuidado infantil,SIN SEGMENTO,ST6,CBB,5602.0,MASIVOS,SBG,Pants Infantil - Especializado
1,JE25651240,KIDGETS YPP LRG/XLRG 4/12'S,Exportaciones VB,KIDGETS,Calzon Entrenador,T5,Top,4.0,12.0,04/12,...,Pants infantil,PERSONAL CARE,Cuidado infantil,SIN SEGMENTO,ST6,CBB,5602.0,MASIVOS,SBG,Pants Infantil - Especializado
2,FS25142341,OUR FAMILY TPP THIN S/4 4/23'S,Exportaciones VB,Our Family,Calzon Entrenador,T4,Top,4.0,23.0,04/23,...,Pants infantil,PERSONAL CARE,Cuidado infantil,SIN SEGMENTO,ST6,CBB,5602.0,MASIVOS,SBG,Pants Infantil - Especializado
3,IA25222540,SHOPKO TPP THIN NINO S/3 4/25'S,Exportaciones VB,SHOPKO,Calzon Entrenador,T3,Unico,4.0,25.0,04/25,...,Pants infantil,PERSONAL CARE,Cuidado infantil,SIN SEGMENTO,ST6,CBB,5602.0,MASIVOS,SBG,Pants Infantil - Especializado
4,5323331260,BABY PANTS C.E T2 6/12 NINA SUPERBABY,Nacional,Baby Pants,Calzon Entrenador,T2,Unico,6.0,12.0,06/12,...,Pants infantil,PERSONAL CARE,Cuidado infantil,MEDIO,ST4,CBB,5602.0,MASIVOS,SBG,Pants Infantil - Especializado

In [13]:
import re
# changue data type
mat_softys.Codigo_Barras_Bolsa = mat_softys.Codigo_Barras_Bolsa.astype(str)
mat_softys.Codigo_Barras_Caja = mat_softys.Codigo_Barras_Caja.astype(str)

mat_softys.Codigo_Barras_Bolsa = [re.sub("^0+", "", ele) for ele in mat_softys.Codigo_Barras_Bolsa]
mat_softys.Codigo_Barras_Caja = [re.sub("^0+", "", ele) for ele in mat_softys.Codigo_Barras_Caja]

# selecting columns
mat_softys=mat_softys.iloc[:,[0,1,7,8,12,13]]

# renaming by index
mat_softys.columns.values[0] = "item_softys"

# drop duplicates with reference of column
mat_softys = mat_softys.drop_duplicates(subset="Codigo_Barras_Caja", inplace=False)
mat_softys = mat_softys.drop_duplicates(subset="Codigo_Barras_Bolsa", inplace=False)

In [14]:
# drop observations
condition = (mat_softys['Bolsas_X_Caja'] == "Material") | \
            (mat_softys['Piezas_X_Bolsa'] == "Material") | \
            (mat_softys['Bolsas_X_Caja'] == 0) | \
            (mat_softys['Piezas_X_Bolsa'] == 0)

# Delete rows based on the condition
mat_softys = mat_softys[~condition]

mat_softys.head(5)

,item_softys,Description,Bolsas_X_Caja,Piezas_X_Bolsa,Codigo_Barras_Caja,Codigo_Barras_Bolsa
0,IF25650943,BABYLOVE GUTE-NACHT YPP LRG/XLRG 4/09'S,4.0,9.0,4010355392558,4010355392541
1,JE25651240,KIDGETS YPP LRG/XLRG 4/12'S,4.0,12.0,10032251302920,32251302923
2,FS25142341,OUR FAMILY TPP THIN S/4 4/23'S,4.0,23.0,170253969031,70253969034
3,IA25222540,SHOPKO TPP THIN NINO S/3 4/25'S,4.0,25.0,10400137646008,400137646001
4,5323331260,BABY PANTS C.E T2 6/12 NINA SUPERBABY,6.0,12.0,10013117001003,13117001006

Melt table: unir en una solo atributo las columnas codigos de barras caja/bolsa

In [15]:
# bolsa

mat_softys_bolsa=mat_softys[["item_softys","Description","Bolsas_X_Caja", "Piezas_X_Bolsa", "Codigo_Barras_Bolsa"]]

mat_softys_bolsa["KEY_UPC_softys"] = mat_softys_bolsa["Codigo_Barras_Bolsa"].astype(str) + mat_softys_bolsa["Piezas_X_Bolsa"].astype(str) + mat_softys_bolsa["Bolsas_X_Caja"].astype(str)

mat_softys_bolsa=mat_softys_bolsa.drop_duplicates(subset=["KEY_UPC_softys"])

mat_softys_bolsa=mat_softys_bolsa.iloc[:,[0,5]]

# caja

mat_softys_caja=mat_softys[["item_softys","Description","Bolsas_X_Caja", "Piezas_X_Bolsa", "Codigo_Barras_Caja"]]

mat_softys_caja["KEY_UPC_softys"] = mat_softys_caja["Codigo_Barras_Caja"].astype(str) + mat_softys_caja["Piezas_X_Bolsa"].astype(str) + mat_softys_caja["Bolsas_X_Caja"].astype(str)

mat_softys_caja=mat_softys_caja.drop_duplicates(subset=["KEY_UPC_softys"])

mat_softys_caja=mat_softys_caja.iloc[:,[0,5]]

In [16]:
# concatenate
mat_softys=pd.concat([mat_softys_bolsa,mat_softys_caja],axis=0)
mat_softys.head(5)

  item_softys       KEY_UPC_softys
0  IF25650943  40103553925419.04.0
1  JE25651240   3225130292312.04.0
2  FS25142341   7025396903423.04.0
3  IA25222540  40013764600125.04.0
4  5323331260   1311700100612.06.0

3) Materiales Power BI

In [17]:
mat_bi=pd.read_excel('/content/drive/Shareddrives/Catalogos_SO/Catalogo_Productos.xlsx',
                     sheet_name="Catalogo")

mat_bi.head(5)

,Agrupador (C+V),Satus SKU,>ATTP5,Madre o hijo,Largo,Inicio (2),Variante (2),Constante(6),>Código Material*,>Desc. Código Material,...,SUBMARCA,Desc_Mayoreo,>ATTP4,>Desc. Sector Material,Segmentacion,>N° Ply / Talla,Presentacion,Empaquetado (Cj/Blt),Unidades,>Kgr_empaq
0,MTY,Big Roll,24/4,NaN,3,AB,11,000855,AB11000855,PH ELITE BIG ROLL DH 47.5 M. NAL 24/4 B,...,Big Roll 400,Big Roll 400 24/4,Tissue,Higienicos,Economico,Doble Hoja,4.0,24.0,96,16.480
1,MTY,Elite Facial,48/180,NaN,3,AB,10,335148,AB10335148,FACIAL MEGA ELITE DISEÑOS HD 48/180 C,...,Facial Mega Licencia,Elite Facial Mega Diseños 48/180,Tissue,Pañuelo/Facial,Alto,Doble Hoja,180.0,48.0,8640,15.724
2,MTY,Elite Neutro,60/32,NaN,3,AB,10,331522,AB10331522,PH ELITE NEUTRO 180TH 16.2M NAC 60/32 B,...,Neutro,Elite Neutro 18016.2M 60/32,Tissue,Higienicos,Premium,Triple Hoja,32.0,60.0,1920,15.115
3,MTY,Elite Facial,48/180,NaN,3,AB,10,335179,AB10335179,PO ELITE FACIAL MEGA SPA DH NAL 48/180,...,Facial Mega Spa,Elite Facial Mega Spa 48/180,Tissue,Pañuelo/Facial,Alto,Doble Hoja,180.0,48.0,8640,14.730
4,MTY,Elite Facial,48/180,NaN,3,AB,10,335315,AB10335315,PO ELITE FACIAL MEGA LAV DH NAL 48/180,...,Facial Mega Lavanda,Elite Facial Mega Lav 48/180,Tissue,Pañuelo/Facial,Alto,Doble Hoja,180.0,48.0,8640,14.730

In [18]:
mat_bi['>Código Material*']=mat_bi['>Código Material*'].astype(str)

mat_bi['>Código Material*'] = [re.sub("^0+", "", ele) for ele in mat_bi['>Código Material*']]

mat_bi=mat_bi.iloc[:,[8]]

mat_bi.columns.values[0] = "item_bi"

mat_bi=mat_bi.replace(r'\s+', ' ', regex=True)

##Tiendas

1) Consumo Z: estan tomando el atributo ZONA y debe ser Cve_Alm

In [29]:
pcz= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda PCZ.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

pcz= pcz.replace(r'\s+', ' ', regex=True) # espacios en blanco

pcz= pcz.iloc[:,[0,1,2]] #seleccionar columnas de interes

pcz= pcz.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
pcz= pcz.rename(columns={'Nombre de Tienda': "Nom_Tda"})  #renombrar una columna

pcz=pcz.iloc[:, [1, 2, 0]] #reordenar columnas by index

pcz.head(3)

  Num_Tda            Nom_Tda Holding
0     159         Dz Arandas      PCZ
1     171  Dz Felipe Angeles      PCZ
2     243        Dz Tlaxiaca      PCZ

2) Garis: ok

In [30]:
garis= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Garis.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

garis = garis.replace(r'\s+', ' ', regex=True) # espacios en blanco en todo el dataset

garis= garis.iloc[:,[0,1,2]] #seleccionar columnas por index

#garis['Nombre de Tienda'] = garis['Nombre de Tienda'].str.replace('Garis', '')  #remplazar nombres

garis= garis.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
garis= garis.rename(columns={'Nombre de Tienda': "Nom_Tda"})

garis=garis.iloc[:, [1,2,0]] #reordenar columnas by index

garis.head(3)

  Num_Tda           Nom_Tda Holding
0     ALM    Garis Almoloya    Garis
1     ALT  Garis Altamirano    Garis
2     CEL      Garis Celaya    Garis

3) Más Bodega

In [31]:
mbodega= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Mas Bodega.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

mbodega= mbodega.iloc[:, [0,1,2]]

mbodega= mbodega.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
mbodega= mbodega.rename(columns={'Nombre de Tienda': "Nom_Tda"})  #renombrar una columna

mbodega['Nom_Tda']=mbodega['Nom_Tda'].str.strip() #eliminar espacios en blanco en toda posicion

mbodega=mbodega.iloc[:, [1, 2, 0]] #reordenar columnas by index

mbodega.head(3)

   Num_Tda                   Nom_Tda    Holding
0       10  Bodega MAS Benito Juarez  Más Bodega
1       13        Bodega MAS Materno  Más Bodega
2       14     Bodega MAS Aeropuerto  Más Bodega

4) Parral, yo creo que si esta bien

In [32]:
parral= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Parral.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

parral['Nombre de Tienda']=parral['Nombre de Tienda'].str.strip() #eliminar espacios en blanco en toda posicion

parral= parral.iloc[:, [0,1,2]]

parral= parral.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
parral= parral.rename(columns={'Nombre de Tienda': "Nom_Tda"})  #renombrar una columna

parral=parral.iloc[:, [1, 2, 0]] #reordenar columnas by index

parral.head(3)

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

   Num_Tda         Nom_Tda             Holding
0        3   Parral Biezma  Abastecedora Parral
1        4  Parral Reforma  Abastecedora Parral
2        5      Parral PRI  Abastecedora Parral

5)Sahuayo

In [33]:
sahuayo= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Sahuayo.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

sahuayo['Nombre de Tienda']=sahuayo['Nombre de Tienda'].str.strip() #eliminar espacios en blanco en toda posicion

sahuayo= sahuayo.iloc[:, [0,1,2]]

sahuayo['Nombre de Tienda'] = sahuayo['Nombre de Tienda'].str.replace('Sahuayo', '')  #remplazar valores
sahuayo['Nombre de Tienda'] = sahuayo['Nombre de Tienda'].str.replace('SAH', '')

sahuayo= sahuayo.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
sahuayo= sahuayo.rename(columns={'Nombre de Tienda': "Nom_Tda"})  #renombrar una columna

sahuayo=sahuayo.iloc[:, [1, 2, 0]] #reordenar columnas by index

sahuayo.head(3)

   Num_Tda         Nom_Tda Holding
0       19     Puebla CEDA  Sahuayo
1       97   Mercado Libre  Sahuayo
2       15        Acapulco  Sahuayo

6) Zorro

In [34]:
zorro= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Zorro Abarrotero.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

zorro= zorro.iloc[:, [0,1,2]]

zorro['Nombre de Tienda'] = zorro['Nombre de Tienda'].str.replace('Zorro', '')  #remplazar valores

zorro= zorro.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
zorro= zorro.rename(columns={'Nombre de Tienda': "Nom_Tda"})  #renombrar una columna

zorro= zorro.iloc[:, [1,2,0]]

zorro.head(3)

  Num_Tda             Nom_Tda Holding
0     CCA   Cazador Comercial    Zorro
1     CNA   Profeta Naucalpan    Zorro
2     CSU        Santa Ursula    Zorro

7) Rivera

In [35]:
from posixpath import split
rivera= pd.read_excel("/content/drive/Shareddrives/Catalogos_SO/Tda Gran Bodega.xlsx", engine="openpyxl") # Explicitly use the openpyxl engine

rivera= rivera.iloc[:, [0,1,2]]

rivera['Nombre de Tienda'] = rivera['Nombre de Tienda'].str.replace('Gran Bodega', '')  #remplazar valores

rivera= rivera.rename(columns={'Código Punto de Venta Cadena': "Num_Tda"})  #renombrar una columna
rivera= rivera.rename(columns={'Nombre de Tienda': "Nom_Tda"})  #renombrar una columna


rivera["codigo"]=rivera["Num_Tda"]

rivera[['#tienda', 'nombre']] = rivera['codigo'].str.split(' ', n=1, expand=True)
rivera=rivera.iloc[:, [0,1,4]]
rivera= rivera.rename(columns={'Num_Tda': "Nom_Tda"})
rivera= rivera.rename(columns={'#tienda': "Num_Tda"})

rivera= rivera.iloc[:, [2,1,0]]

rivera.head(3)

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

  Num_Tda   Nom_Tda     Holding
0      10  10 XILOT  Gran Bodega
1      12    12 MOM  Gran Bodega
2      13   13 CAPU  Gran Bodega

Dataframe de toda las tiendas

In [36]:
tdas=pd.concat([pcz,garis,mbodega,sahuayo,zorro,rivera,parral])

tdas=tdas.drop_duplicates()
tdas= tdas.replace(r'\s+', ' ', regex=True)

tdas.head(5)

  Num_Tda            Nom_Tda Holding
0     159         Dz Arandas      PCZ
1     171  Dz Felipe Angeles      PCZ
2     243        Dz Tlaxiaca      PCZ
3     239        Dz Zumpango      PCZ
4     237  Dz Nicolas Romero      PCZ

#Ruta SOS

In [37]:
import pandas as pd
import glob

##Archivos individuales

In [ ]:
BASE_PATH = "/content/drive/MyDrive/Sell Out/Dbyte_SO/Mensuales"

# Read Excel files into DataFrames
#df1 = pd.read_excel(BASE_PATH + '/SOHistoricosSep-Oct2023.xlsx')
#df2 = pd.read_excel(BASE_PATH + '/SOHistoricosEne-Mar2023.xlsx')
df3 = pd.read_excel(BASE_PATH + '/SOHistoricosEne-Feb2024.xlsx')
#df4 = pd.read_excel(BASE_PATH + '/SOHistoricosNov-Dic2023.xlsx')
df5 = pd.read_excel(BASE_PATH + '/SOHistoricosMar-Abr24.xlsx')
df6 = pd.read_excel(BASE_PATH + '/SoHistoricosSep-Oct2024.xlsx')
#df7 = pd.read_excel(BASE_PATH + '/SOHistoricosJul-Ago2023.xlsx')
df8 = pd.read_excel(BASE_PATH + '/SOHistoricoJul-Ago2024.xlsx')
df9 = pd.read_excel(BASE_PATH + '/SoHistoricosMay-Jun2024.xlsx')
#df10 =pd.read_excel(BASE_PATH + '/SOHistoricosAbr-Jun2023.xlsx')

##Concatenado

In [ ]:
df_vertical = pd.concat([df3, df5, df6, df8, df9], axis=0)   # axis=1 si fuera en horizontal

df_vertical=df_vertical.replace(r'\s+',' ', regex=True)

In [ ]:
df_vertical.tail()

,Grupo Comecial,Cadena,Subcadena,Tienda,UPC,SKU,Descripcion de Producto,Unidades,Cajas,Año mes
511128,Zorro,Zorro,Zorro,ZZU,00013117022858,2202128,Bbtips Sensitive Alto Pañal T7 04/40,28.0,7.00,2024 06 Jun
511129,Zorro,Zorro,Zorro,ZZU,00013117029567,2202117,Affective Protect Adulto T4 04/10,6.0,1.50,2024 05 May
511130,Zorro,Zorro,Zorro,ZZU,00013117029567,2202117,Affective Protect Adulto T4 04/10,18.0,4.50,2024 06 Jun
511131,Zorro,Zorro,Zorro,ZZU,00013117032512,2202129,Classic Economico Pañal T7 04/40,4.0,1.00,2024 05 May
511132,Zorro,Zorro,Zorro,ZZU,00013117032512,2202129,Classic Economico Pañal T7 04/40,9.0,2.25,2024 06 Jun

In [ ]:
df_vertical.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2589364 entries, 0 to 511132
Data columns (total 10 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Grupo Comecial           object
 1   Cadena                   object
 2   Subcadena                object
 3   Tienda                   object
 4   UPC                      object
 5   SKU                      object
 6   Descripcion de Producto  object
 7   Unidades                 float64
 8   Cajas                    float64
 9   Año mes                  object
dtypes: float64(2), object(8)
memory usage: 217.3+ MB

##Filtrado

In [ ]:
df_vertical["Grupo Comecial"].unique()

array(['Abarrotes Rivera', 'Al Super', 'Amazon', 'Calimax', 'Casa Ley',
       'Chedraui', 'City Club', 'Consumo Z', 'Control',
       'Farmacias Benavides', 'Farmacon', 'Garis', 'HEB', 'La Comer',
       'Mas Bodega', 'Mercado Libre', 'Merco', 'Oxxo', 'Parral',
       'Sahuayo', 'Sams', 'Sanborns', 'Soriana', 'Super Kompras',
       'Wal-Mart', 'Zorro'], dtype=object)

In [ ]:
# Lista de cadenas
mayoristas = ['Abarrotes Rivera','Consumo Z','Garis',"Mas Bodega",'Parral','Sahuayo','Zorro']

# Filter DataFrame por lista
df_vertical = df_vertical[df_vertical["Grupo Comecial"].isin(mayoristas)]

##Transformaciones

Eliminar ceros a la izquierda

In [ ]:
#esto no intera a nivel fila, es más rápido el proceso
df_vertical.UPC = df_vertical.UPC.astype(str)

import re
df_vertical.UPC = [re.sub("^0+", "", ele) for ele in df_vertical.UPC]

Eliminar columnas

In [ ]:
df_vertical.head()

,Grupo Comecial,Tienda,UPC,SKU,Descripcion de Producto,Cajas,Año mes
0,Abarrotes Rivera,9,13117000689,23DCHI009,Bbtips Sensitive Alto Pañal T2 04/40,23.50,2024 01 Ene
1,Abarrotes Rivera,9,13117000689,23DCHI009,Bbtips Sensitive Alto Pañal T2 04/40,15.25,2024 02 Feb
2,Abarrotes Rivera,9,13117000696,23DCHI010,Bbtips Sensitive Alto Pañal T3 04/40,22.75,2024 01 Ene
3,Abarrotes Rivera,9,13117000696,23DCHI010,Bbtips Sensitive Alto Pañal T3 04/40,17.50,2024 02 Feb
4,Abarrotes Rivera,9,13117000702,23DCHI011,Bbtips Sensitive Alto Pañal T4 04/40,35.25,2024 01 Ene

In [ ]:
df_vertical = df_vertical.drop ('Cadena', axis = 1)
df_vertical = df_vertical.drop ('Subcadena', axis = 1)
df_vertical = df_vertical.drop ('Unidades', axis = 1)
#df_vertical = df_vertical.drop ('Año Mes', axis = 1)

KeyError: "['Cadena'] not found in axis"

Conversion de datos

In [ ]:
df_vertical["Cajas"] = df_vertical["Cajas"].astype(float)

Fecha

In [ ]:
# Seperacion de caracteres en columnas
df_vertical[['Año', 'Mes', "NomMes"]] = df_vertical['Año mes'].str.split(' ', expand=True)

In [ ]:
df_vertical["fecha"]=df_vertical.Año.astype(str)+"-"+df_vertical.Mes.astype(str) +"-01"
df_vertical["fecha"] = pd.to_datetime(df_vertical["fecha"], errors='coerce', format='%Y-%m-%d')

Missign Data

In [ ]:
print("Missing values distribution: ")
print(df_vertical.isnull().sum() * 100 / len(df_vertical))
print("")

Missing values distribution:
Grupo Comecial             0.0
Tienda                     0.0
UPC                        0.0
SKU                        0.0
Descripcion de Producto    0.0
Cajas                      0.0
Año mes                    0.0
Año                        0.0
Mes                        0.0
NomMes                     0.0
fecha                      0.0
dtype: float64

Negativos == 0 || Registros > 0

In [ ]:
import numpy as np

df_vertical['Cajas'] = np.where(df_vertical['Cajas'] < 0, 0, df_vertical['Cajas']) #negativos a positivos

df_vertical=df_vertical[(df_vertical["Cajas"]>0)]

In [ ]:
df_vertical[df_vertical.isna().any(axis=1)]  #revisar registros con datos faltantes

Empty DataFrame
Columns: [Grupo Comecial, Tienda, UPC, SKU, Descripcion de Producto, Cajas, Año mes, Año, Mes, NomMes, fecha]
Index: []

#Merge

In [ ]:
import re

df=df_vertical.iloc[:,[0,1,2,3,4,5,10]]

*Tiendas BI*

In [ ]:
# catalogo de tiendas
df_tdas= df.merge(tdas, left_on="Tienda", right_on="Num_Tda", how="left")

* Eliminar tiendas

In [ ]:
# condicion a cumplir
condition = (df_tdas['Tienda'] == "DLS") | \
            (df_tdas['Tienda'] == "67")

# Delete rows based on the condition
df_tdas = df_tdas[~condition]

* Cambio de tiendas

In [ ]:
df_tdas["Tienda"] = df_tdas["Tienda"].replace(["0"], "11") #Parral

*Materiales*

Cuando existen una columna de otro data set con el mismo nombre de la tabla de hecho a la cual se hará la busqueda (columna pivote), entonces solo se trae del dataset los otros atributos excepto la columna con nombre en comun :D

**1) Catalogo Dbyte:** se necesita conocer el Key_UPN al que hace refrencia la descarga (conteos, factor de caja, UPN/IPN) para que este se pueda vincular al catalogo generales de materiales de Puebla.

In [ ]:
# catalogo de materiales UPC
df_prod= df_tdas.merge(UPC, left_on="UPC", right_on="UPC", how="left")

**Resultados del merge: 1er paso**

In [ ]:
print("Missing values distribution: ")
print(df_prod.isnull().sum() * 100 / len(df_prod))
print("")

Missing values distribution:
Grupo Comecial              0.000000
Tienda                      0.000000
UPC                         0.000000
SKU                         0.000000
Descripcion de Producto     0.000000
Cajas                       0.000000
fecha                       0.000000
Num_Tda                    30.624086
Nom_Tda                    30.624086
Holding                    30.624086
KEY_UPC_dbyte               0.000000
dtype: float64

**2) Catalogo Puebla:** una vez conociendo el Key_UPC de dbyte, es necesario vincularlo con el KEY_UPC_Softys para que considerar un unico codigo, una sola descripcion, y una sola caracterización de los productos (porque un EAN tiene multiples variables y descripciones)

In [ ]:
# renombrar Key_UPC_Dbyte con KEY_UPC_softys del catalogo de materiales

df_prod=df_prod.rename(columns={'KEY_UPC_dbyte': "KEY_UPC_softys"})

# catalogo general de productos Puebla

df_prod= df_prod.merge(mat_softys_bolsa, left_on="KEY_UPC_softys", right_on="KEY_UPC_softys", how="left")

> La razon del porque tengo datos faltantes en el Item Softys obedece siempre al numero de piezas por bolsa o las bolsas por caja. Por ello es necesario cambiar la relaciones del UPC en los productos

In [ ]:
print("Missing values distribution: ")
print(df_prod.isnull().sum() * 100 / len(df_prod))
print("")

Missing values distribution:
Grupo Comecial              0.000000
Tienda                      0.000000
UPC                         0.000000
SKU                         0.000000
Descripcion de Producto     0.000000
Cajas                       0.000000
fecha                       0.000000
Num_Tda                    30.624086
Nom_Tda                    30.624086
Holding                    30.624086
KEY_UPC_softys              0.000000
item_softys                23.232860
dtype: float64

Exportar los codigos que no aparecen en "catalogo de materiales de Puebla"

In [ ]:
# exportar el codigo de UPC para integrarlo al catalogo general
#UPC=df_merg["item_softys"].unique()
#UPC=pd.DataFrame(UPC)
#UPC.to_csv('UPC.csv', index=False)

#Tabla dinamica

In [ ]:
df_prod.head()

,Grupo Comecial,Tienda,UPC,SKU,Descripcion de Producto,Cajas,fecha,Num_Tda,Nom_Tda,Holding,KEY_UPC_softys,item_softys
0,Abarrotes Rivera,9,13117000689,23DCHI009,Bbtips Sensitive Alto Pañal T2 04/40,23.50,2024-01-01,9,9 U.COM,Gran Bodega,13117000689404,2715524040
1,Abarrotes Rivera,9,13117000689,23DCHI009,Bbtips Sensitive Alto Pañal T2 04/40,15.25,2024-02-01,9,9 U.COM,Gran Bodega,13117000689404,2715524040
2,Abarrotes Rivera,9,13117000696,23DCHI010,Bbtips Sensitive Alto Pañal T3 04/40,22.75,2024-01-01,9,9 U.COM,Gran Bodega,13117000696404,2715534040
3,Abarrotes Rivera,9,13117000696,23DCHI010,Bbtips Sensitive Alto Pañal T3 04/40,17.50,2024-02-01,9,9 U.COM,Gran Bodega,13117000696404,2715534040
4,Abarrotes Rivera,9,13117000702,23DCHI011,Bbtips Sensitive Alto Pañal T4 04/40,35.25,2024-01-01,9,9 U.COM,Gran Bodega,13117000702404,2715544040

In [ ]:
# seleccion de columnas
sos=df_prod.iloc[:,[2,3,4,5,6,7,8,9,11]]

# reordenado de columnas
sos=sos.iloc[:,[4,7,5,6,8,3,2,0]]
#sos.dropna(inplace=True)

In [ ]:
pivot_table=pd.pivot_table(data=sos,
                           index=["fecha","Holding ", "Num_Tda", "Nom_Tda","item_softys", "Descripcion de Producto","UPC"],
                           values=["Cajas"],
                           aggfunc=np.sum,
                           fill_value=0)

#exportar tabla dinamica
pivot_table.reset_index().to_excel('sos.xlsx',sheet_name = 'Sheet1',index=False)

<ipython-input-135-4a760d7dda29>:1: FutureWarning: The provided callable <function sum at 0x7d99a61fc670> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_table=pd.pivot_table(data=sos,